apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
spec:
  type: NodePort
  selector:
    role: frontend
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30080
--- 
apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
spec:
  type: NodePort
  selector:
    role: backend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: db-nodeport
spec:
  type: NodePort
  selector:
    role: db
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306